# Generated by Django 6.0.5 on 2026-09-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_merge_appliance_device_room'),
        ('telemetry', '0011_timescale_hypertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('socket_id', models.PositiveSmallIntegerField(db_index=True)),
                ('label', models.CharField(choices=[('RESISTIVE', 'Resistive - bulb, heater, iron'), ('SMPS', 'Switching supply - charger, LED driver, TV'), ('MIXED', 'Mixed - active PFC, or two loads'), ('NONE', 'Nothing detected')], db_index=True, max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(default='rule', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('crest', models.FloatField(default=0.0)),
                ('form_factor', models.FloatField(default=0.0)),
                ('conduction', models.FloatField(default=0.0)),
                ('thd', models.FloatField(default=0.0)),
                ('h3', models.FloatField(default=0.0)),
                ('h5', models.FloatField(default=0.0)),
                ('rms_adc', models.FloatField(default=0.0)),
                ('cycle', models.JSONField(blank=True, default=list)),
                ('device_label', models.CharField(blank=True, default='', max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_signatures', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device_id', 'socket_id', '-timestamp'], name='telemetry_l_device__d62c2c_idx')],
            },
        ),
    ]
